SOURCES = $(wildcard *.md)
SLIDES  = $(SOURCES:.md=.html)
PDFS  = $(SOURCES:.md=.pdf)
TMP_PDFS = $(wildcard tmp-slides-*.pdf)

COMMON_DIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
PANDOCCMD=pandoc --to revealjs --template $(COMMON_DIR)revealjs-template.pandoc --standalone --section-divs --no-highlight
PHANTOMCMD=phantomjs ../phantomjs-revealjs-slide-capture.js
GSCMD=gs -q -dPDFSETTINGS=/printer -dNOPAUSE -dBATCH -sDEVICE=pdfwrite

#.PHONY: all clean

foo:
	echo $(COMMON_DIR)

all: $(SLIDES)

%.pdf: %.html
	@echo "building $@ from $<" && \
	$(PHANTOMCMD) $< && \
	$(GSCMD) -sOutputFile=$@ $$(ls tmp-slide-*.pdf) && \
	rm -f $$(ls tmp-slide-*.pdf)


%.html: %.md
	@echo "building $@ from $<" && \
	$(PANDOCCMD) $< -o build/$@

clean:
	-rm -f *.html *.pdf
