# to configure project Makefile following lines need to be added
IMAGE_NAME = adsy/training_builder_arch
NEXT_VERSION = v001
#IMAGE_DESCRIPTION = "tcs-cardispo2-backend"

build:
	docker build -t $(IMAGE_NAME):$(NEXT_VERSION) .
